[directory]
style = 'bold blue'

[aws]
disabled = true
symbol = 'aws '

[cmake]
disabled = true
symbol = 'cmake '

[deno]
disabled = true
symbol = 'deno '

[docker_context]
disabled = true
symbol = 'docker '

[dotnet]
disabled = true
symbol = 'dotnet '

[git_branch]
symbol = ''
style = 'bold purple'

[golang]
disabled = true
symbol = 'go '

[java]
disabled = true
symbol = 'java '

[lua]
disabled = true
symbol = 'lua '

[nodejs]
disabled = true
symbol = 'node '

[package]
disabled = true
symbol = 'package '

[perl]
disabled = true
symbol = 'perl '

[python]
disabled = true
symbol = 'python '

[ruby]
disabled = true
symbol = 'ruby '

[rust]
disabled = true
symbol = 'rust '

[scala]
disabled = true
symbol = 'scala '

[username]
disabled = true

[hostname]
disabled = true

[time]
disabled = false
use_12hr = true
