command_timeout = 500

[aws]
disabled = true
symbol = ''

[character]
symbol = '➜'
error_symbol = '➜'
use_symbol_for_status = true

[git_branch]
symbol = ''

[java]
disabled = true
symbol = 'java '

[nodejs]
disabled = true
symbol = 'node '

[package]
disabled = true

[python]
disabled = true
symbol = 'python '

[ruby]
disabled = true
symbol = 'ruby '

[time]
disabled = false
use_12hr = true
