require('nvim-treesitter.configs').setup({
  ensure_installed = {
    'bash',
    'c',
    'c_sharp',
    'comment',
    'cpp',
    'go',
    'graphql',
    'html',
    'javascript',
    'json',
    'json5',
    'lua',
    'regex',
    'ruby',
    'rust',
    'toml',
    'tsx',
    'typescript',
    'vim',
  },
  highlight = {
    enable = true,
    disable = { "html" },
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<CR>",
      node_incremental = "<CR>",
      -- scope_incremental = "<CR>",
      node_decremental = "<BS>",
    },
  },
})
